package cn.edu.pku.lixutian.graph;

import cn.edu.pku.lixutian.config.ClusterState;
import cn.edu.pku.lixutian.graph.softwareGraph.SoftwareGraph;
import cn.edu.pku.lixutian.graph.softwareGraph.arc.CallArc;
import cn.edu.pku.lixutian.graph.softwareGraph.arc.ClassArc;
import cn.edu.pku.lixutian.graph.softwareGraph.arc.ReferenceArc;
import cn.edu.pku.lixutian.graph.softwareGraph.vertex.Vertex;
import cn.edu.pku.lixutian.graph.softwareGraph.vertex.VertexMap;
import cn.edu.pku.lixutian.graph.softwareGraph.arc.Arc;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.body.CallableDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.expr.AnnotationExpr;

import java.util.*;
import java.util.stream.Collectors;

public class SKG extends SoftwareGraph<Arc> {
    private static SKG instance;

    public static SKG getInstance() {
        assert instance != null;
        return instance;
    }

    public static SKG getNewInstance() {
        instance = new SKG();
        return instance;
    }

    private VertexMap vertexMap = null;
    private ClassGraph classGraph = null;
    private ReferenceGraph referenceGraph = null;
    private CallGraph callGraph = null;

    public SKG() {
    }

    private NodeList<CompilationUnit> compilationUnits = null;

    /**
     * implements Buildable&lt;T&gt;
     */
    @Override
    public void build(NodeList<CompilationUnit> nodeList) {
        if (isBuilt()) {
            return;
        }
        compilationUnits = nodeList;
        System.out.println("==========1. Building VertexMap & StaticDesc ==========");
        vertexMap = VertexMap.getNewInstance();
        vertexMap.build(nodeList);
        System.out.println("==========2. Building ClassGraph==========");
        classGraph = ClassGraph.getNewInstance();
        classGraph.build(nodeList);
        System.out.println("==========3. Building ReferenceGraph==========");
        referenceGraph = ReferenceGraph.getNewInstance();
        referenceGraph.build(nodeList);
        System.out.println("==========4. Building CallGraph==========");
        callGraph = CallGraph.getNewInstance();
        callGraph.build(nodeList);
        System.out.println("==========5. Building SKG==========");
        buildVertices();
        buildEdges();
        built = true;
    }

    @Override
    protected void buildVertices() {
        vertexMap.getAllVertexMap().forEach((t1, map) -> {
            map.forEach((t2, vertex) -> {
                addVertex(vertex);
            });
        });
    }

    @Override
    protected void buildEdges(NodeList<CompilationUnit> arg, Set<String> unsolvedSymbols) {
        buildEdges();
    }

    private void buildEdges() {
        Set<Arc> arcs = new HashSet<>();
        arcs.addAll(classGraph.edgeSet());
        arcs.addAll(referenceGraph.edgeSet());
        arcs.addAll(callGraph.edgeSet());
        arcs.forEach(arc -> {
            addEdge(arc.getSource(), arc.getTarget(), arc);
        });
    }

    private List<String> getEntries() {
        return vertexMap.getMethodDeclarationMap().entrySet().stream()
                // 没有 Caller 的 Method
                .filter(entry -> {
                    long callArcCount = incomingEdgesOf(entry.getValue()).stream()
                            .filter(arc -> arc instanceof CallArc)
                            .count();
                    return callArcCount == 0;
                })
                //
                .filter(entry -> {
                    CallableDeclaration<?> methodDeclaration = entry.getValue().getDeclaration();
                    // isAbstract
                    if (methodDeclaration.isAbstract()) {
                        return false;
                    }
                    // isAutoGenerated
                    for (AnnotationExpr annotation : methodDeclaration.getAnnotations()) {
                        if (annotation.getNameAsString().equals("lombok.Generated")
                                || annotation.getNameAsString().equals("ltm.Generated")) {
                            return false;
                        }
                    }
                    return true;
                })
                .map(Map.Entry::getKey)
                .toList();
    }

    public void cluster() {
        List<String> entryMethodIds = getEntries();

        for (int i = 1; i <= entryMethodIds.size(); i++) {
            slice(entryMethodIds.get(i - 1), i);
        }
    }

    public void slice(String sc, int clusterId) {
        Vertex<?> vertex = vertexMap.getMethodDeclaration(sc);

        Deque<Vertex<?>> bfsQueue = new LinkedList<>();
        Set<Vertex<?>> methodSet = new HashSet<>();
        Set<Vertex<?>> fieldSet = new HashSet<>();
        Set<Vertex<?>> typeSet = new HashSet<>();

        // 添加入口点
        vertex.getClusterIds().add(clusterId);
        methodSet.add(vertex);
        boolean hasModified = true;

        // Method => Method, Field(NormalField/AnnotationMember), Type(enum)
        while (hasModified) {
            hasModified = false;
            // 1. 方法挖所有调用方法
            // Method => Method
            slice1Methods2AllCalledMethods(clusterId, methodSet, fieldSet, typeSet, bfsQueue);
            // 2. 方法 /字段挖引用（字段（普通字段、注解字段）、枚举类）
            // 2.1 Method => Field(NormalField/AnnotationMember), Type(enum)
            // 2.2 Field => Field(NormalField/AnnotationMember), Type(enum)
            slice2MethodsFields2UseReferences(clusterId, methodSet, fieldSet, typeSet, bfsQueue);
            // 3. 字段（普通字段、注解字段）挖相关方法
            // Field => Method
            hasModified |= slice3Fields2RelatedMethods(clusterId, methodSet, fieldSet, typeSet, bfsQueue);
        }

        // Method, Field => Type
        // 4. 方法 /字段挖关联类型
        slice4MethodsFields2ReferencedTypes(clusterId, methodSet, fieldSet, typeSet, bfsQueue);
        // 5. 方法 /字段挖上级类
        slice5MethodsFields2MemberedTypes(clusterId, methodSet, fieldSet, typeSet, bfsQueue);

        // 6. 类别挖父类/外部类/注解
        // Type => Type
        slice6Types2AllTypes(clusterId, methodSet, fieldSet, typeSet, bfsQueue);

    }

    // 方法 /字段挖引用（字段（普通字段、注解字段）、枚举类）
    private void slice1Methods2AllCalledMethods(int clusterId, Set<Vertex<?>> methodSet,
                                                Set<Vertex<?>> fieldSet, Set<Vertex<?>> typeSet,
                                                Deque<Vertex<?>> bfsQueue) {
        bfsQueue.addAll(methodSet);
        Set<Vertex<?>> visited = new HashSet<>();
        visited.addAll(methodSet);
        while (!bfsQueue.isEmpty()) {
            Vertex<?> currentVertex = bfsQueue.poll();
            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof CallArc.NormalCallArc) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    if (!visited.contains(candidateVertex)) {
                        bfsQueue.add(candidateVertex);
                        visited.add(candidateVertex);
                        candidateVertex.getClusterIds().add(clusterId);
                        methodSet.add(candidateVertex);
                    }
                    arc.getClusterIds().add(clusterId);
                }
            }
        }
    }

    // 挖方法、字段引用，字段（普通字段、注解字段）、枚举类
    private void slice2MethodsFields2UseReferences(int clusterId, Set<Vertex<?>> methodSet,
                                                   Set<Vertex<?>> fieldSet, Set<Vertex<?>> typeSet,
                                                   Deque<Vertex<?>> bfsQueue) {
        // 1. 挖方法引用
        bfsQueue.addAll(methodSet);
        for (Vertex<?> currentVertex : methodSet) {
            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof ReferenceArc.MethodReference.UseReference) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    candidateVertex.getClusterIds().add(clusterId);
                    if (candidateVertex.getDeclaration().isEnumDeclaration()) {
                        typeSet.add(candidateVertex);
                    } else {
                        fieldSet.add(candidateVertex);
                    }
                    arc.getClusterIds().add(clusterId);
                }
            }
        }

        // 2. 挖字段引用
        bfsQueue.addAll(fieldSet);
        Set<Vertex<?>> visited = new HashSet<>();
        visited.addAll(fieldSet);
        while (!bfsQueue.isEmpty()) {
            Vertex<?> currentVertex = bfsQueue.poll();
            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof ReferenceArc.MethodReference.UseReference) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    if (!visited.contains(candidateVertex)) {
                        bfsQueue.add(candidateVertex);
                        visited.add(candidateVertex);
                        candidateVertex.getClusterIds().add(clusterId);
                        if (candidateVertex.getDeclaration().isEnumDeclaration()) {
                            typeSet.add(candidateVertex);
                        } else {
                            fieldSet.add(candidateVertex);
                        }
                    }
                    arc.getClusterIds().add(clusterId);
                }
            }
        }
    }

    // 字段（普通字段、注解字段）挖相关方法
    private boolean slice3Fields2RelatedMethods(int clusterId, Set<Vertex<?>> methodSet,
                                                Set<Vertex<?>> fieldSet, Set<Vertex<?>> typeSet,
                                                Deque<Vertex<?>> bfsQueue) {

        bfsQueue.addAll(fieldSet);
        boolean hasModified = false;
        for (Vertex<?> currentVertex : bfsQueue) {
            // 1. 字段被 Initializer 初始化
            for (Arc arc : incomingEdgesOf(currentVertex)) {
                if (arc instanceof ReferenceArc.MethodReference.UseReference.FieldDef) {
                    Vertex<?> candidateVertex = arc.getSource();
                    if (candidateVertex.getDeclaration().isInitializerDeclaration()) {
                        hasModified |= candidateVertex.getClusterIds().add(clusterId);
                        methodSet.add(candidateVertex);
                        hasModified |= arc.getClusterIds().add(clusterId);
                    }
                }
            }

            // 2. 带初始化调用的字段挖调用的方法
            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof CallArc.NormalCallArc) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    hasModified |= candidateVertex.getClusterIds().add(clusterId);
                    methodSet.add(candidateVertex);
                    hasModified |= arc.getClusterIds().add(clusterId);
                }
            }
        }
        return hasModified;
    }

    // 方法 /字段挖关联类型
    private void slice4MethodsFields2ReferencedTypes(int clusterId, Set<Vertex<?>> methodSet,
                                                     Set<Vertex<?>> fieldSet, Set<Vertex<?>> typeSet,
                                                     Deque<Vertex<?>> bfsQueue) {
        bfsQueue.addAll(methodSet);
        bfsQueue.addAll(fieldSet);
        for (Vertex<?> currentVertex : bfsQueue) {
            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof ReferenceArc.FieldReference ||
                        arc instanceof ReferenceArc.MethodReference ||
                        arc instanceof ReferenceArc.AnnotationReference
                ) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    candidateVertex.getClusterIds().add(clusterId);
                    typeSet.add(candidateVertex);
                    arc.getClusterIds().add(clusterId);
                }
            }
        }
    }

    // 方法 /字段挖上级类
    private void slice5MethodsFields2MemberedTypes(int clusterId, Set<Vertex<?>> methodSet,
                                                   Set<Vertex<?>> fieldSet, Set<Vertex<?>> typeSet,
                                                   Deque<Vertex<?>> bfsQueue) {
        bfsQueue.addAll(methodSet);
        bfsQueue.addAll(fieldSet);
        for (Vertex<?> currentVertex : bfsQueue) {
            for (Arc arc : incomingEdgesOf(currentVertex)) {
                if (arc instanceof ClassArc.MemberArc) {
                    Vertex<?> candidateVertex = arc.getSource();
                    candidateVertex.getClusterIds().add(clusterId);
                    typeSet.add(candidateVertex);
                    arc.getClusterIds().add(clusterId);
                }
            }
        }
    }

    // 类别挖父类/外部类/注解
    private void slice6Types2AllTypes(int clusterId, Set<Vertex<?>> methodSet,
                                      Set<Vertex<?>> fieldSet, Set<Vertex<?>> typeSet,
                                      Deque<Vertex<?>> bfsQueue) {
        bfsQueue.addAll(typeSet);
        Set<Vertex<?>> visited = new HashSet<>();
        visited.addAll(typeSet);
        while (!bfsQueue.isEmpty()) {
            Vertex<?> currentVertex = bfsQueue.poll();

            // 1. 类别挖父类/外部类
            for (Arc arc : incomingEdgesOf(currentVertex)) {
                if (arc instanceof ClassArc.ParentArc || arc instanceof ClassArc.InnerArc) {
                    Vertex<?> candidateVertex = arc.getSource();
                    if (!visited.contains(candidateVertex)) {
                        bfsQueue.add(candidateVertex);
                        visited.add(candidateVertex);
                        candidateVertex.getClusterIds().add(clusterId);
                        typeSet.add(candidateVertex);
                    }
                    arc.getClusterIds().add(clusterId);
                }
            }

            // 2. 类别挖注解类
            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof ReferenceArc.AnnotationReference) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    if (!visited.contains(candidateVertex)) {
                        bfsQueue.add(candidateVertex);
                        visited.add(candidateVertex);
                        candidateVertex.getClusterIds().add(clusterId);
                        typeSet.add(candidateVertex);
                    }
                    arc.getClusterIds().add(clusterId);
                }
            }
        }
    }

//    public SKG getMinGraph() {
//        SKG minGraph = new SKG();
//        Set<Integer> candidateClusterIds = ClusterState.getInstance().getClusterIds();
//        vertexSet().stream()
//                .filter(vertex -> candidateClusterIds.containsAll(vertex.getClusterIds()))
//                .forEach(vertex -> minGraph.addVertex(vertex));
//
//        edgeSet().stream()
//                .filter(edge -> candidateClusterIds.containsAll(edge.getClusterIds()))
//                .filter(edge -> minGraph.vertexSet().contains(edge.getSource()) && minGraph.vertexSet().contains(edge.getTarget()))
//                .forEach(edge -> minGraph.addEdge(edge.getSource(), edge.getTarget(), edge));
//
//        return minGraph;
//    }

    public SKG getMaxGraph() {
        SKG maxGraph = new SKG();
        Set<Integer> candidateClusterIds = ClusterState.getInstance().getClusterIds();
        if (candidateClusterIds == null) {
            return maxGraph;
        } else {
            vertexSet().stream()
                    .filter(vertex -> !Collections.disjoint(candidateClusterIds, vertex.getClusterIds()))
                    .forEach(vertex -> maxGraph.addVertex(vertex));

            edgeSet().stream()
                    .filter(edge -> !Collections.disjoint(candidateClusterIds, edge.getClusterIds()))
                    .forEach(edge -> maxGraph.addEdge(edge.getSource(), edge.getTarget(), edge));
            return maxGraph;
        }

    }

    public SKG getSlicedGraphByClass(Vertex<TypeDeclaration<?>> topVertex) {
        SKG slicedGraph = new SKG();
        slicedGraph.addVertex(topVertex);
        Deque<Vertex<?>> bfsQueue = new ArrayDeque<>();
        bfsQueue.add(topVertex);
        Set<Vertex<?>> visited = new HashSet<>();
        visited.add(topVertex);

        while (!bfsQueue.isEmpty()) {
            Vertex<?> currentVertex = bfsQueue.poll();

            for (Arc arc : outgoingEdgesOf(currentVertex)) {
                if (arc instanceof ClassArc.MemberArc || arc instanceof ClassArc.InnerArc) {
                    Vertex<?> candidateVertex = arc.getTarget();
                    if (!visited.contains(candidateVertex)) {
                        bfsQueue.add(candidateVertex);
                        visited.add(candidateVertex);
                        slicedGraph.addVertex(candidateVertex);
                    }
                    slicedGraph.addEdge(arc.getSource(), arc.getTarget(), arc);
                }
            }
        }
        return slicedGraph;
    }

    public void debloating(Set<Integer> targetClusterIds) {
        // 1. 找需要删除的顶点
        Set<Vertex<?>> verticesToRemove = vertexSet().stream()
                .filter(v -> targetClusterIds.containsAll(v.getClusterIds()))
                .collect(Collectors.toSet());

        // 2. 找需要删除的边（只要 source 或 target 在删除顶点内）
        Set<Arc> edgesToRemove = edgeSet().stream()
                .filter(e -> targetClusterIds.contains(e.getClusterIds()))
                .collect(Collectors.toSet());

        // 3. 暂存
        Set<Vertex<?>> removedVertices = new HashSet<>();
        Set<Arc> removedArcs = new HashSet<>();

        removedVertices.addAll(verticesToRemove);
        removedArcs.addAll(edgesToRemove);

        // 4. 正式删除：先删边，再删点
//        removeAllEdges(edgesToRemove);
//        removeAllVertices(verticesToRemove);

        System.out.println("aaa111");
        for (Integer clusterId : targetClusterIds) {
            System.out.println(clusterId);
        }
        System.out.println("aaa222");
        for (Vertex<?> vertex : verticesToRemove) {
            System.out.println(vertex.getDeclaration().toString());
        }
    }
}
